version: '3'

services:
  app:
    build: .
    ports:
      - "5000:8081"
    depends_on:
      - postgres
  postgres:
    build:
      dockerfile: db.Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 60s
        delay: 3s
      resources:
        limits:
          cpus: '0.50'
          memory: '100M'
        reservations:
          cpus: '0.20'
          memory: '15M'
